version: '3.0'
services:

  ### NGINX #########################################
  nginx:
    container_name: my_nginx
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=1.17
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./www/:/data/www:rw
      - ./logs/nginx/:/var/log/nginx

  ### MySQL ################################################
  mysql:
    container_name: my_mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=latest
    environment:
      - MYSQL_ROOT_PASSWORD=root # 必须要设置这个
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  ### Redis ################################################
  redis:
    container_name: my_redis
    build:
      context: ./redis
      args:
        - REDIS_VERSION=latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: --requirepass ${REDIS_PASSWORD}

  ### Redis Cluster ##########################################
  redis-cluster:
    container_name: my_redis_cluster
    build:
      context: ./redis-cluster
    ports:
      - "7000-7005:7000-7005"

  ### Gitlab ################################################
  gitlab:
    container_name: my_gitlab
    build:
      context: ./gitlab
      args:
        - GITLAB_VERSION=latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.exmail.qq.com'
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = 'xxx@qq.com'
        gitlab_rails['smtp_password'] = 'xxx'
        gitlab_rails['smtp_domain'] = 'qq.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_root_email'] = 'xxx@qq.com'
        gitlab_rails['initial_root_password'] = 'Qwe@123456'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab@localhost'
        gitlab_rails['gitlab_email_display_name'] = 'Ryan'
    ports:
      - "8989:80"
      - "9898:443"
    volumes:
      - ./data/gitlab/config:/etc/gitlab # 挂载gitlab配置文件
      - ./data/gitlab/data:/var/opt/gitlab # 挂载gitlab数据
      - ./logs/gitlab:/var/log/gitlab # 挂载gitlab日志

    restart: always

  ### Jenkins #########################################
  jenkins:
    container_name: my_jenkins
    build:
      context: ./jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
